### ISSUE TITLE
Possible to get the click position inside a div while using ng2-right-click

### ISSUE THREAD

**Issue by Ekaanth** [sarsha17/sarsha17.github.io#2]
Hello,

Currently, I'm using ng2-right-click and I need to know the position of my click so that I can place another component there. Currently, on click, the event is emitting only
`{menuItem: {…}, dataContext: {…}}`
is there a way so that I get the click position from the event or ant workaround will work
Thanks.

**Comment by msarsha** [comment]
moved to msarsha/ng2-right-click-menu#58
